In [1]:
print("Hello world")

Hello world


In [4]:
print("Hello")

Hello


In [5]:
arr=[1,2,3,4]
print(arr)

[1, 2, 3, 4]


In [6]:
print(type(arr))

<class 'list'>


In [7]:
import numpy as np

In [9]:
b=np.array(arr)

In [10]:
print(type(b))

<class 'numpy.ndarray'>


In [12]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [13]:
a.ndim

1

In [14]:
a=[[1,2,3],[4,5,6]]
print(a)

[[1, 2, 3], [4, 5, 6]]


In [15]:
print(type(a))

<class 'list'>


In [16]:
b=np.array(a)
print(b)

[[1 2 3]
 [4 5 6]]


In [17]:
type(b)

numpy.ndarray

In [18]:
b.ndim

2

In [19]:
b.shape

(2, 3)

In [20]:
b.size

6

In [21]:
b.dtype

dtype('int32')

In [22]:
b.itemsize

4

In [23]:
b.data

In [24]:
a=[[[1,2,3],[4,5,6],[7,8,9]]]
print(a)
type(a)

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]


list

In [28]:
b=np.array(a)
print(b)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [29]:
b.ndim

3

In [30]:
d=[[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]]
print(d)
print(type(d))

[[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]]]
<class 'list'>


In [31]:
e=np.array(d)
print(e)

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [10 11 12]]]]


In [32]:
e.ndim

4

In [33]:
e.shape

(1, 1, 4, 3)

In [34]:
e.dtype

dtype('int32')

In [35]:
e.itemsize

4

In [36]:
e.data

In [39]:
e=np.zeros([2,2])

In [40]:
np.zeros(e.shape)

array([[0., 0.],
       [0., 0.]])

In [43]:
np.zeros(b.shape)

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])