In [1]:
a=[[1,2,3],[4,5,6],[7,8,9]]
print(a)
print(type(a))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>


In [2]:
import numpy as np
b=np.array(a)
print(type(b))

<class 'numpy.ndarray'>


In [3]:
a=np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
np.zeros(3)

array([0., 0., 0.])

In [5]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.zeros((3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [6]:
import numpy as np
np.full((3,4),2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [8]:
np.random.rand(3,5)

array([[0.76562096, 0.59131811, 0.87824507, 0.55001314, 0.66006347],
       [0.44484653, 0.31805034, 0.10528342, 0.28114926, 0.32904104],
       [0.40166572, 0.92650578, 0.28422384, 0.89197145, 0.77429276]])

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
abc=np.copy(a)
print(abc)

[1 2 3 4 5]


In [12]:
array1=np.array([9,6,8,5,2])
array2=np.array([1,7,4,0,3])
v=np.concatenate((array1,array2),axis=0)
print(v)

[9 6 8 5 2 1 7 4 0 3]


In [13]:
array3=np.array([[1,2,3,4],[5,6,7,8]])
array4=np.array([[5,7,6,8],[9,3,1,2]])
s=np.concatenate((array3,array4),axis=1)
print(s)

[[1 2 3 4 5 7 6 8]
 [5 6 7 8 9 3 1 2]]


In [14]:
array5=np.array([1,2,3,4])
s=np.split(array5,4)
print(s)

[array([1]), array([2]), array([3]), array([4])]


In [15]:
s=array5[3]
print(s)

4


In [16]:
s=array5[3]=6
print(s)
print(array5)

6
[1 2 3 6]


In [17]:
array1.view()

array([9, 6, 8, 5, 2])

In [18]:
s=array5[1:3]=4
print(s)
print(array5)

4
[1 4 4 6]


In [19]:
s=array5[0:4]
print(s)
print(array5)

[1 4 4 6]
[1 4 4 6]


In [20]:
print(array1)
array1[0:2]

[9 6 8 5 2]


array([9, 6])

In [21]:
print(array3)
array3[0:1,3]

[[1 2 3 4]
 [5 6 7 8]]


array([4])

In [8]:
import numpy as np
np.full((3,4),2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])