In [10]:
#sklearn- Lab1
# Linear Regression Model

In [11]:
import numpy as np
import pandas as pd

In [12]:
df=pd.read_csv('iris.csv')
df

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [13]:
#y=ax+c
#:rain #testing   supervised ML
#80:20
df['variety'].value_counts()

Setosa        50
Versicolor    50
Virginica     50
Name: variety, dtype: int64

In [14]:
x=df.iloc[:,0:4].values # filter Independent variable
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [15]:
y=df.iloc[:,4].values  # filter dependent variable
y

array(['Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolo

In [16]:
#convert Y in numbers encoding

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
labelencoder_y= LabelEncoder()

In [21]:
y=labelencoder_y.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
x_train

array([[6.3, 2.7, 4.9, 1.8],
       [5.4, 3. , 4.5, 1.5],
       [4.8, 3.1, 1.6, 0.2],
       [4.3, 3. , 1.1, 0.1],
       [5.1, 3.7, 1.5, 0.4],
       [6.9, 3.1, 5.4, 2.1],
       [5.2, 2.7, 3.9, 1.4],
       [6.1, 3. , 4.6, 1.4],
       [6.5, 3. , 5.5, 1.8],
       [5.8, 2.8, 5.1, 2.4],
       [5.2, 3.4, 1.4, 0.2],
       [5.9, 3.2, 4.8, 1.8],
       [5. , 3.5, 1.3, 0.3],
       [6. , 3. , 4.8, 1.8],
       [5.8, 2.7, 3.9, 1.2],
       [4.4, 2.9, 1.4, 0.2],
       [5.5, 2.4, 3.7, 1. ],
       [6.7, 3. , 5.2, 2.3],
       [5.5, 3.5, 1.3, 0.2],
       [5.7, 2.5, 5. , 2. ],
       [7.6, 3. , 6.6, 2.1],
       [6.1, 2.6, 5.6, 1.4],
       [4.5, 2.3, 1.3, 0.3],
       [6.1, 3. , 4.9, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [5.4, 3.4, 1.7, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5.9, 3. , 5.1, 1.8],
       [5.2, 3.5, 1.5, 0.2],
       [7.2, 3. , 5.8, 1.6],
       [6.3, 3.3, 6. , 2.5],
       [5.5, 2.4, 3.8, 1.1],
       [7. , 3.2, 4.7, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [4.8, 3

In [24]:
x_train.size

420

In [25]:
x_test.size

180

In [26]:
y_train.size

105

In [27]:
y_test.size

45

In [28]:
from sklearn.linear_model import LogisticRegression

In [36]:
logmodel=LogisticRegression()
logmodel.fit(x_train,y_train)

LogisticRegression()

In [35]:
logmodel.fit(x_train,y_train)

LogisticRegression()

In [37]:
y_pred= logmodel.predict(x_test)
y_pred

array([0, 2, 0, 2, 0, 1, 0, 1, 2, 1, 1, 1, 2, 1, 0, 2, 1, 2, 2, 1, 2, 2,
       2, 0, 2, 2, 1, 1, 1, 2, 0, 0, 0, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 0,
       1], dtype=int64)

In [39]:
y_pred
np.sort(y_pred)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2], dtype=int64)

In [40]:
y_test
np.sort(y_pred)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2], dtype=int64)

In [41]:
from sklearn.metrics import confusion_matrix

In [42]:
confusion_matrix(y_test,y_pred)

array([[13,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 14]], dtype=int64)

In [43]:
(28/30)*100

93.33333333333333

In [44]:
logmodel.score(x_test,y_test)

0.9777777777777777

In [50]:
from sklearn.neighbors import KNeighborsClassifier

In [51]:
classifier_knn=KNeighborsClassifier(n_neighbors=5, metric='minkowski',p=2) #distance time

In [52]:
classifier_knn.fit(x_train,y_train)

KNeighborsClassifier()

In [54]:
y_pred_knn=classifier_knn.predict(x_test)
y_pred_knn

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([0, 2, 0, 2, 0, 1, 0, 1, 2, 1, 1, 1, 2, 1, 0, 2, 1, 2, 2, 2, 1, 2,
       2, 0, 2, 2, 1, 1, 1, 2, 0, 0, 0, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 0,
       1], dtype=int64)

In [55]:
from sklearn.metrics import confusion_matrix

In [56]:
confusion_matrix(y_test,y_pred_knn)

array([[13,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 14]], dtype=int64)

In [57]:
classifier_knn.score(x_test,y_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


0.9777777777777777

In [59]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred_knn,y_test)

0.9777777777777777

In [60]:
# Naivebaise model

In [62]:
from sklearn.naive_bayes import GaussianNB

In [65]:
classifier_nb= GaussianNB()
classifier_nb

GaussianNB()

In [66]:
classifier_nb.fit(x_train,y_train)

GaussianNB()

In [67]:
y_pred=classifier_nb.predict(x_test)
y_pred

array([0, 2, 0, 2, 0, 1, 0, 1, 2, 1, 1, 1, 2, 1, 0, 2, 1, 2, 2, 1, 2, 2,
       2, 0, 2, 2, 1, 1, 1, 2, 0, 0, 0, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 0,
       1], dtype=int64)